name: example-api
settings:

model:
  - tablename: users
    fields:
      - name: id
        datatype: INTEGER
        constraints: PRIMARY KEY NOT NULL
      - name: email
        datatype: VARCHAR(255)
        constraints: null
  - tablename: posts
    fields:
      - name: id
        datatype: INTEGER
        constraints: PRIMARY KEY NOT NULL
      - name: email
        datatype: VARCHAR(255)
        constraints: null
      - name: content
        datatype: TEXT
        constraints: null
endpoint:
  - description: List users
    path: users
    method: GET
    table: users
    op: get_by_id
    endpoint:
  - description: List posts
    path: posts
    method: GET
    table: posts
    op: get_by_id
